### ISSUE TITLE
Definir como vamos lidar com os dados dos tickets antigos (pré-match-otimizado).

### ISSUE THREAD

**Issue by talitanovacoski** [nossas/bonde-redes#244]

**Comment by vivianedias** [comment]
Caso uma MSR se inscreva mais de uma vez e o ticket anterior dela de pedido de acolhimento não tenha sido encaminhado, vamos criar um novo ticket para essa MSR, com "status do acolhimento: solicitação repetida" e inserir uma referência a esse primeiro ticket de acolhimento que foi criado para ela, no novo. 

Esse novo portanto entrará na pipeline do match automatizado, e o match será feito em referência à aquele primeiro pedido de ajuda. 

No fim, os tickets antigos continuarão abertos, e não serão endereçados diretamente - quem deve criar alguma ação referente a eles são as próprias MSRs que vão reafirmar seu pedido.
