### ISSUE TITLE
Na busca da data de inscrição no bonde da voluntária retornar a data do primeiro cadastro

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-redes#61]

**Comment by lpirola** [comment]
Vale dizer que vai ser importante também deixar marcado como external_id no zendesk, o id do form_entries. E buscar por celular ao invés de e-mail a informação que tem maior consistência sobre a voluntária.

**Comment by lpirola** [comment]
@vivianedias aproveitar que vamos atualizar essa info, vale checar se estamos atualizando a data de inscrição da voluntária no zendesk.

**Comment by vivianedias** [comment]
Vou validar isso hj! @lpirola

**Comment by vivianedias** [comment]
**Na usuária**, retornaremos a data do mais novo cadastro através do campo "data_de_inscrição_do_bonde". O histórico das datas de cada cadastro (vezes que submeteram seus dados no formulário do BONDE) **estarão nos tickets.**
